version: '3.8'

services:
  react-app:
    image: node:20-alpine
    working_dir: /app/skin
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
